#This deploys a function on the Function App plan
name: Deploy App - Function proj to Azure Function App

on:
 workflow_dispatch:
    inputs:
      subscriptionId:
        description: 'SubscriptionId'
        required: true
      resourceGroupName:
        description: 'Resource group name'
        required: true
        default: 'rg-ais-demos'
      functionAppName:
        description: 'Function App name'
        required: true
        default: 'snowvro7891011'

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: funcservicenow  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './function'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1'              # set this to the dotnet version to use

jobs:
  deploy-function:
      runs-on: windows-latest
      environment: dev
      steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{github.event.inputs.functionAppName}} 
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
