# This deploys the Logic Apps app (no workflow)

name: Deploy Infra - LogicApps-App

# Controls when the action will run. 
on:
 workflow_dispatch:
    inputs:
      subscriptionId:
        description: 'SubscriptionId'
        required: true 
        default: '8bcaf808-26b1-45e4-8340-ec627a7afa0a'
      resourceGroupName:
        description: 'Resource group name'
        required: true
        default: 'rg-aisdemo'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{github.event.inputs.subscriptionId}}
          resourceGroupName: ${{github.event.inputs.resourceGroupName}}
          template: ./infra/logicapp-plan.json
          parameters: ./infra/logicapp-plan.parameters.json
